spring.application.name=catonese
spring.datasource.url=jdbc:mysql://localhost:3306/catonese?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

lessons.content-folder=lessons

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.show_sql=false

alignment.base-url=http://localhost:8000

spring.servlet.multipart.enabled=true
